-- 0028_platform_seed.down.sql
-- GENERATED by scripts/extract-mockup-spec.ts — removes the seeded IA rows only.
-- Never touches elements / checklist_items / resources / storage.

begin;
delete from public.platform_extras;
delete from public.platform_topics;
delete from public.platform_groups;
delete from public.platform_sections;
commit;
