-- 0028_platform_seed.up.sql
-- GENERATED by scripts/extract-mockup-spec.ts from the owner's final mockup (as amended by
-- D-PP-c: 3-card model, extras dropped) — do not hand-edit; re-run the script instead.
-- Idempotent: upserts keyed on stable natural keys (sections.slug,
-- groups (section_slug, slug), topics element_id via elements.slug).
-- Requires 0027_platform_ia. Safe to re-run; never touches elements/checklists/resources rows.

begin;

-- Sections (5 = the About landing + the 4 toolkit pages)
insert into public.platform_sections
  (slug, num, label, subtitle, eyebrow, title, lead, hero_image_path, hero_position,
   journey_image_path, journey_image_position, journey_desc, journey_icon, sort_order)
values
  ('about', 0, 'About', null, 'Palestine House · Partner Knowledge Platform', 'Everything you need for your House.', 'Find practical guidance, tools, and support across Setup, Operate, Program, and Support.', '/assets/workspace/heroes/about.jpg', '50% 50%', null, null, null, null, 0),
  ('setup', 1, 'Setup', 'Setup Toolkit', 'Setup', 'Setup', 'Open the foundations, standards, systems, and practical guidance for establishing a new House.', '/assets/workspace/heroes/setup.jpg', '50% 50%', '/assets/workspace/sections/setup.jpg', '50% 54%', 'Open the foundations, standards, systems, and practical guidance for establishing a new House.', 'compass', 1),
  ('operate', 2, 'Operate', 'Operations', 'Operate', 'Operate', 'Find day-to-day guidance across facilities, food and beverage, people, finance, governance, and compliance.', '/assets/workspace/heroes/operate.jpg', '50% 52%', '/assets/workspace/sections/operate.jpg', '50% 50%', 'Find day-to-day guidance across facilities, food and beverage, people, finance, governance, and compliance.', 'house', 2),
  ('program', 3, 'Program', 'Programming', 'Program', 'Program', 'Plan programming, membership, partnerships, marketing, campaigns, and retail with the related tools close by.', '/assets/workspace/heroes/program.jpg', '50% 46%', '/assets/workspace/sections/program.jpg', '50% 50%', 'Plan programming, membership, partnerships, marketing, campaigns, and retail with the related tools close by.', 'calendar', 3),
  ('support', 4, 'Support', 'Support', 'Support', 'Support', 'Use shared network resources and send one clear question to HQ when your team needs support.', '/assets/workspace/heroes/support.jpg', '50% 44%', '/assets/workspace/sections/support.jpg', '50% 54%', 'Use shared network resources and send one clear question to HQ when your team needs support.', 'life-buoy', 4)
on conflict (slug) do update set
  num = excluded.num, label = excluded.label, subtitle = excluded.subtitle,
  eyebrow = excluded.eyebrow, title = excluded.title, lead = excluded.lead,
  hero_image_path = excluded.hero_image_path, hero_position = excluded.hero_position,
  journey_image_path = excluded.journey_image_path, journey_image_position = excluded.journey_image_position,
  journey_desc = excluded.journey_desc, journey_icon = excluded.journey_icon,
  sort_order = excluded.sort_order;

-- Groups (10)
insert into public.platform_groups (section_slug, slug, name, description, sort_order)
values
  ('setup', 'setup-toolkit', 'Setup toolkit', 'Choose the area you are working on.', 1),
  ('operate', 'run-the-house-day-to-day', 'Run the House day to day', 'Building, service, suppliers and stock.', 1),
  ('operate', 'people-hr', 'People / HR', 'Roles, hiring, training and team culture.', 2),
  ('operate', 'finance-reporting-and-kpis', 'Finance, reporting & KPIs', 'Revenue, controls, reports and audits.', 3),
  ('operate', 'governance-compliance-and-risk', 'Governance, compliance & risk', 'Decisions, ethics, legal duties and risk.', 4),
  ('operate', 'cafe-and-culinary-program', 'Café & culinary program', 'Menu, drinks, catering and culinary events.', 5),
  ('program', 'programming-with-aswatna', 'Programming with Aswātna', 'Plan and deliver cultural programming.', 1),
  ('program', 'membership-and-community-partnerships', 'Membership & community partnerships', 'Grow membership and build local relationships.', 2),
  ('program', 'marketing-local-global-and-retail', 'Marketing (local + global) & retail', 'Promote the House and run the shop.', 3),
  ('support', 'support-toolkit', 'Support toolkit', 'Find shared tools or ask HQ for help.', 1)
on conflict (section_slug, slug) do update set
  name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;

-- Topics (33) — keyed on element_id resolved from the verified elements.slug map.
-- A missing element slug fails the not-null constraint loudly rather than seeding wrong.
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'i2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'setup' and pg.slug = 'setup-toolkit'),
  'launching-a-new-house', 'Launching a New House', 'Guidance and files to help you prepare your House.', 'Everything you need to open a new Palestine House, step by step — from first planning to opening day. Read the guide, then use the templates below to get the work done.', 'compass',
  '/assets/workspace/topics/launching-a-new-house.jpg', '50% 54%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'b1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'setup' and pg.slug = 'setup-toolkit'),
  'operating-model', 'Operating Model', 'How a House is structured, decides, and reports.', 'This explains how a Palestine House is run: who does what, how decisions are made, and how your House works with HQ. Use it to set up your House the right way from day one.', 'network',
  '/assets/workspace/topics/operating-model.jpg', '50% 53%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'a1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'setup' and pg.slug = 'setup-toolkit'),
  'mission-values-and-guest-promise', 'Mission, Values and Guest Promise', 'The charter every House runs on — and how to live it daily.', 'This tells you what Palestine House stands for and the promise every guest must feel when they walk in. Use it to make sure your whole team understands the mission and lives it every day.', 'heart',
  '/assets/workspace/topics/mission-values-and-guest-promise.jpg', '50% 52%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'a3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'setup' and pg.slug = 'setup-toolkit'),
  'brand-experience-standards', 'Brand Experience Standards', 'What the brand looks, sounds, and feels like — and HQ approvals.', 'This shows you exactly how the Palestine House brand must look and feel in your House — from signage to events. Use it to keep everything on-brand and to know when to ask HQ for approval.', 'sparkles',
  '/assets/workspace/topics/brand-experience-standards.jpg', '50% 54%', 4
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'i1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'setup' and pg.slug = 'setup-toolkit'),
  'technology-stack-and-data', 'Technology Stack & Data', 'The systems every House runs on.', 'This covers the systems and tools your House uses, and how to handle data safely. Use it to set up your technology correctly and keep information protected.', 'database',
  '/assets/workspace/topics/technology-stack-and-data.jpg', '50% 55%', 5
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'f1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'run-the-house-day-to-day'),
  'facility-operations', 'Facility Operations', 'Open, run, and close the building safely.', 'This covers how to keep your building safe, clean, and running smoothly every day. Use it for daily routines, maintenance, and opening and closing the House.', 'building',
  '/assets/workspace/topics/facility-operations.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'f2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'run-the-house-day-to-day'),
  'food-and-beverage-operations', 'Food & Beverage Operations', 'The café floor: service, safety, standards.', 'This covers how to run your café and kitchen safely and to standard every day. Use it for food safety, service routines, and daily kitchen operations.', 'utensils',
  '/assets/workspace/topics/food-and-beverage-operations.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'f3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'run-the-house-day-to-day'),
  'inventory-and-procurement', 'Inventory & Procurement', 'Buying, suppliers, and stock counts.', 'This shows you how to buy, receive, and track everything your House needs — without waste or surprises. Use it to manage suppliers, stock, and orders.', 'box',
  '/assets/workspace/topics/inventory-and-procurement.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'e2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'run-the-house-day-to-day'),
  'customer-service-and-recovery', 'Customer Service & Recovery', 'Great service — and fixing it when it goes wrong.', 'This shows your team how to serve guests well and how to fix things quickly when something goes wrong. Use it to handle complaints and turn a bad moment into a good one.', 'smile',
  '/assets/workspace/topics/customer-service-and-recovery.jpg', '50% 50%', 4
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'c1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'people-hr'),
  'org-structure-and-roles', 'Org Structure & Roles', 'Who does what — roles, org chart, responsibilities.', 'This explains the team structure of a Palestine House and what each role is responsible for. Use it to build your team and make sure everyone knows their job.', 'users',
  '/assets/workspace/topics/org-structure-and-roles.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'c2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'people-hr'),
  'hiring-onboarding-and-training', 'Hiring, Onboarding & Training', 'Find, welcome, and train your team.', 'This shows you how to find the right people, welcome them properly, and train them to standard. Use it every time you bring someone new into the team.', 'user-plus',
  '/assets/workspace/topics/hiring-onboarding-and-training.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'c3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'people-hr'),
  'performance-management-and-culture', 'Performance Management & Culture', 'Reviews, feedback, and a healthy team culture.', 'This shows you how to help your team perform well and keep a healthy, positive culture. Use it for reviews, feedback, and recognising good work.', 'line-chart',
  '/assets/workspace/topics/performance-management-and-culture.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'h1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'finance-reporting-and-kpis'),
  'business-model-and-revenue', 'Business Model & Revenue', 'Where the money comes from.', 'This explains how a Palestine House earns money and stays financially healthy. Use it to understand your revenue streams and plan for a sustainable House.', 'coins',
  '/assets/workspace/topics/business-model-and-revenue.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'h2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'finance-reporting-and-kpis'),
  'financial-operations-and-controls', 'Financial Operations & Controls', 'Day-to-day money handling, done properly.', 'This covers the day-to-day money rules: handling cash, paying bills, and keeping clean records. Use it to run your finances safely and avoid costly mistakes.', 'calculator',
  '/assets/workspace/topics/financial-operations-and-controls.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'h3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'finance-reporting-and-kpis'),
  'reporting-kpis-and-audits', 'Reporting, KPIs & Audits', 'What to report to HQ, and when.', 'This shows you what to measure, what to report to HQ, and how audits work. Use it to track how your House is doing and to report on time.', 'bar-chart',
  '/assets/workspace/topics/reporting-kpis-and-audits.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'b2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'governance-compliance-and-risk'),
  'governance-and-ethics', 'Governance & Ethics', 'Boards, accountability, and the non-negotiables.', 'This explains the rules of good governance and ethical behaviour every House must follow. Use it to make decisions properly and protect the trust people place in Palestine House.', 'shield-check',
  '/assets/workspace/topics/governance-and-ethics.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'b3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'governance-compliance-and-risk'),
  'legal-compliance-and-risk', 'Legal, Compliance & Risk', 'Entity, permits, contracts, and staying protected.', 'This covers the legal requirements your House must meet and the risks to watch for. Use it to stay compliant and deal with problems before they grow.', 'scale',
  '/assets/workspace/topics/legal-compliance-and-risk.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'k1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'cafe-and-culinary-program'),
  'menu-and-palestinian-culinary-identity', 'Menu & Palestinian Culinary Identity', 'A menu that tells the story of Palestine.', 'This shows you how to build a menu that tells the story of Palestinian food — authentic, consistent, and profitable. Use it to develop dishes, price them, and keep the culinary identity strong.', 'chef-hat',
  '/assets/workspace/topics/menu-and-palestinian-culinary-identity.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'k2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'cafe-and-culinary-program'),
  'coffee-tea-and-beverage-program', 'Coffee, Tea & Beverage Program', 'The drinks program, from qahwa to service.', 'This covers how to serve coffee, tea, and drinks to a high, consistent standard — including the qahwa and tea rituals. Use it to train baristas, care for the equipment, and get every cup right.', 'coffee',
  '/assets/workspace/topics/coffee-tea-and-beverage-program.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'k3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'operate' and pg.slug = 'cafe-and-culinary-program'),
  'catering-private-events-and-culinary-programming', 'Catering, Private Events & Culinary Programming', 'Food beyond the café: catering and events.', 'This shows you how to sell and deliver catering, private events, and food experiences. Use it to quote, plan, and run food events smoothly and profitably.', 'utensils',
  '/assets/workspace/topics/catering-private-events-and-culinary-programming.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'd1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'programming-with-aswatna'),
  'programming-model-and-pillars', 'Programming Model & Pillars', 'What a House programs, and why.', 'This explains the kind of cultural programming a Palestine House runs and the pillars behind it. Use it to plan a calendar of events that fits the mission.', 'calendar',
  '/assets/workspace/topics/programming-model-and-pillars.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'd2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'programming-with-aswatna'),
  'aswatna-studio-collaboration', 'Aswātna Studio Collaboration', 'Working with your cultural programming partner.', 'This shows you how to work with Aswātna Studio on content and creative projects. Use it to plan collaborations and know exactly who does what.', 'music',
  '/assets/workspace/topics/aswatna-studio-collaboration.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'd3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'programming-with-aswatna'),
  'event-production-sops', 'Event Production SOPs', 'Run every event to the same standard.', 'This gives you the step-by-step way to produce an event, from planning to pack-down. Use it every time you run an event so nothing is missed.', 'ticket',
  '/assets/workspace/topics/event-production-sops.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'a2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'membership-and-community-partnerships'),
  'guest-journey-and-member-journey', 'Guest Journey & Member Journey', 'From first visit to loyal member, step by step.', 'This shows the full journey from first-time guest to loyal member, and what to do at every step. Use it to welcome guests, invite them to join, and keep members engaged.', 'route',
  '/assets/workspace/topics/guest-journey-and-member-journey.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'e1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'membership-and-community-partnerships'),
  'membership-model-and-benefits', 'Membership Model & Benefits', 'The membership offer and how to grow it.', 'This explains how membership works: the tiers, the prices, and the benefits. Use it to sell memberships clearly and deliver what members are promised.', 'badge',
  '/assets/workspace/topics/membership-model-and-benefits.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'e3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'membership-and-community-partnerships'),
  'community-partnerships', 'Community Partnerships', 'Build lasting local partnerships.', 'This shows you how to build partnerships with local organisations and communities. Use it to find the right partners and agree on how you work together.', 'handshake',
  '/assets/workspace/topics/community-partnerships.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'g1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'marketing-local-global-and-retail'),
  'local-marketing-playbook', 'Local Marketing Playbook', 'Fill the House from your own city.', 'This shows you how to market your House locally and fill it with the right guests. Use it to plan campaigns, social media, and local outreach.', 'megaphone',
  '/assets/workspace/topics/local-marketing-playbook.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'g2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'marketing-local-global-and-retail'),
  'global-campaigns', 'Global Campaigns', 'Join network-wide campaigns from HQ.', 'This explains the global campaigns run by HQ and your House''s part in them. Use it to join campaigns on time and use the official materials correctly.', 'globe',
  '/assets/workspace/topics/global-campaigns.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'g3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'program' and pg.slug = 'marketing-local-global-and-retail'),
  'retail-shop-operations', 'Retail Shop Operations', 'Run the shop: range, display, sales.', 'This covers how to run the retail shop: what to sell, how to display it, and how to manage the stock. Use it to make the shop a strong part of your House.', 'shopping-bag',
  '/assets/workspace/topics/retail-shop-operations.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'i3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'support' and pg.slug = 'support-toolkit'),
  'crisis-management', 'Crisis Management', 'What to do in the first hour — and after.', 'This shows you what to do when something serious goes wrong — from emergencies to reputation issues. Use it to act fast, keep people safe, and inform HQ the right way.', 'siren',
  '/assets/workspace/topics/crisis-management.jpg', '50% 50%', 1
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'j3'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'support' and pg.slug = 'support-toolkit'),
  'sustainability-and-impact', 'Sustainability & Impact', 'Fund the mission and measure the impact.', 'This explains how your House reduces its footprint and measures the good it creates. Use it to run more sustainably and report your impact.', 'leaf',
  '/assets/workspace/topics/sustainability-and-impact.jpg', '50% 50%', 2
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'j1'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'support' and pg.slug = 'support-toolkit'),
  'continuous-improvement-and-knowledge-sharing', 'Continuous Improvement & Knowledge Sharing', 'Learn, improve, and share it with the network.', 'This shows you how to keep making your House better and share what you learn with the network. Use it to fix recurring problems and pass on what works.', 'refresh-cw',
  '/assets/workspace/topics/continuous-improvement-and-knowledge-sharing.jpg', '50% 50%', 3
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;
insert into public.platform_topics
  (element_id, group_id, slug, title, description, intro, icon, image_path, image_position, sort_order)
select
  (select e.id from public.elements e where e.slug = 'j2'),
  (select pg.id from public.platform_groups pg where pg.section_slug = 'support' and pg.slug = 'support-toolkit'),
  'templates-and-master-index', 'Templates & Master Index', 'Every template in the network, indexed.', 'This is the map of every template on the platform and where to find it. Use it when you need a specific working file, fast.', 'files',
  '/assets/workspace/topics/templates-and-master-index.jpg', '50% 50%', 4
on conflict (element_id) do update set
  group_id = excluded.group_id, slug = excluded.slug, title = excluded.title,
  description = excluded.description, intro = excluded.intro, icon = excluded.icon,
  image_path = excluded.image_path, image_position = excluded.image_position,
  sort_order = excluded.sort_order;

commit;
