/* GENERATED by scripts/extract-mockup-spec.ts — do not hand-edit; re-run the script.
 *
 * The workspace v2 shell copy, verbatim from the owner's final mockup (the same
 * extraction that writes docs/workspace-spec.json). Kept as a generated module
 * rather than a JSON import because the full spec is ~167 KB and only this slice
 * is needed at module scope. Section/topic content comes from the database. */

export const WORKSPACE_CHROME = {
  "skipLink": "Skip to content",
  "brand": {
    "href": "https://www.palestine-house.com/",
    "ariaLabel": "Palestine House — public home page",
    "logoAlt": "Palestine House — Our Culture Embassy"
  },
  "nav": {
    "ariaLabel": "Partner platform",
    "mobileAriaLabel": "Partner platform, mobile",
    "items": [
      {
        "page": "about",
        "label": "About",
        "tip": "Start here."
      },
      {
        "page": "setup",
        "label": "Setup",
        "tip": "Get the foundations right."
      },
      {
        "page": "operate",
        "label": "Operate",
        "tip": "Run the House."
      },
      {
        "page": "program",
        "label": "Program",
        "tip": "Plan experiences."
      },
      {
        "page": "support",
        "label": "Support",
        "tip": "Get help."
      }
    ]
  },
  "account": {
    "label": "Partner Platform",
    "ariaLabel": "Open Partner Platform"
  },
  "menuButton": {
    "ariaLabel": "Open menu"
  },
  "documentTitleSuffix": "Palestine House Partner Platform",
  "footer": {
    "cta": {
      "heading": "Need help finding the right resource?",
      "lead": "Search every guide and template, or send one clear question to HQ.",
      "searchAction": "Search all resources",
      "askAction": "Ask HQ",
      "photoAlt": "Guests gathered at a lantern-lit Palestine House doorway"
    },
    "brand": {
      "logoAlt": "Palestine House — Our Culture Embassy",
      "blurb": "A clear, shared home for every guide, checklist, video, and template your House needs.",
      "arabic": "بيت فلسطين في كل مدينة"
    },
    "columns": [
      {
        "title": "Platform",
        "links": [
          "About",
          "Setup",
          "Operate"
        ],
        "context": []
      },
      {
        "title": "Knowledge",
        "links": [
          "Program",
          "Support",
          "Search everything"
        ],
        "context": []
      },
      {
        "title": "Account",
        "links": [
          "Partner Platform"
        ],
        "context": [
          "Private access for approved Palestine House partners."
        ]
      },
      {
        "title": "Help",
        "links": [
          "Ask HQ"
        ],
        "context": [
          "Live files and permissions connect through the authenticated platform."
        ]
      }
    ],
    "bottom": {
      "tagline": "Passion inspires. Discipline delivers.",
      "copyright": "© Palestine House · Partner Platform"
    }
  }
} as const;

export const PLATFORM_PAGES = {
  "about": {
    "label": "About",
    "eyebrow": "Palestine House · Partner Knowledge Platform",
    "title": "Everything you need for your House.",
    "lead": "Find practical guidance, tools, and support across Setup, Operate, Program, and Support.",
    "heroImage": "/assets/workspace/heroes/about.jpg",
    "heroPosition": "50% 50%"
  },
  "setup": {
    "label": "Setup",
    "eyebrow": "Setup",
    "title": "Setup",
    "lead": "Open the foundations, standards, systems, and practical guidance for establishing a new House.",
    "heroImage": "/assets/workspace/heroes/setup.jpg",
    "heroPosition": "50% 50%"
  },
  "operate": {
    "label": "Operate",
    "eyebrow": "Operate",
    "title": "Operate",
    "lead": "Find day-to-day guidance across facilities, food and beverage, people, finance, governance, and compliance.",
    "heroImage": "/assets/workspace/heroes/operate.jpg",
    "heroPosition": "50% 52%"
  },
  "program": {
    "label": "Program",
    "eyebrow": "Program",
    "title": "Program",
    "lead": "Plan programming, membership, partnerships, marketing, campaigns, and retail with the related tools close by.",
    "heroImage": "/assets/workspace/heroes/program.jpg",
    "heroPosition": "50% 46%"
  },
  "support": {
    "label": "Support",
    "eyebrow": "Support",
    "title": "Support",
    "lead": "Use shared network resources and send one clear question to HQ when your team needs support.",
    "heroImage": "/assets/workspace/heroes/support.jpg",
    "heroPosition": "50% 44%"
  }
} as const;

export const PLATFORM_JOURNEY = [
  {
    "page": "setup",
    "num": "1",
    "icon": "compass",
    "title": "Setup",
    "desc": "Open the foundations, standards, systems, and practical guidance for establishing a new House.",
    "action": "Explore",
    "image": "/assets/workspace/sections/setup.jpg",
    "imagePosition": "50% 54%"
  },
  {
    "page": "operate",
    "num": "2",
    "icon": "house",
    "title": "Operate",
    "desc": "Find day-to-day guidance across facilities, food and beverage, people, finance, governance, and compliance.",
    "action": "Explore",
    "image": "/assets/workspace/sections/operate.jpg",
    "imagePosition": "50% 50%"
  },
  {
    "page": "program",
    "num": "3",
    "icon": "calendar",
    "title": "Program",
    "desc": "Plan programming, membership, partnerships, marketing, campaigns, and retail with the related tools close by.",
    "action": "Explore",
    "image": "/assets/workspace/sections/program.jpg",
    "imagePosition": "50% 50%"
  },
  {
    "page": "support",
    "num": "4",
    "icon": "life-buoy",
    "title": "Support",
    "desc": "Use shared network resources and send one clear question to HQ when your team needs support.",
    "action": "Explore",
    "image": "/assets/workspace/sections/support.jpg",
    "imagePosition": "50% 54%"
  }
] as const;

export type WorkspaceNavItem = (typeof WORKSPACE_CHROME.nav.items)[number];
export type PlatformPageKey = keyof typeof PLATFORM_PAGES;
